# Generated by Django 4.0.6 on 2022-08-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('iban', models.TextField(max_length=24)),
                ('tipo_de_cuenta', models.TextField(max_length=20, null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('user_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.TextField(max_length=100)),
                ('monto', models.IntegerField()),
                ('tipo_operacion', models.TextField(max_length=200)),
                ('hora', models.DateTimeField()),
            ],
        ),
    ]
