# Generated by Django 4.0.6 on 2022-08-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_cuenta_account_id_cuenta_tipo_de_cuenta_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_de_cuenta_id',
        ),
    ]
