# Generated by Django 4.0.6 on 2022-08-31 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0004_alter_cuenta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={},
        ),
    ]
