# Generated by Django 4.0.6 on 2022-09-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0005_alter_cuenta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='account_id',
            field=models.IntegerField(default=1),
        ),
    ]
