# Generated by Django 4.0.6 on 2022-09-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0006_cuenta_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='account_id',
        ),
    ]
