# Generated by Django 4.0.6 on 2022-08-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('name', models.TextField(max_length=40)),
                ('surname', models.TextField(max_length=25)),
                ('dni', models.IntegerField()),
                ('direccion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('iban', models.TextField(max_length=100)),
                ('tipo_de_cuenta_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.TextField(max_length=100)),
                ('employee_surname', models.TextField(max_length=100)),
                ('employee_hire_date', models.TextField(max_length=300)),
                ('employee_dni', models.TextField(max_length=100)),
                ('branch_id', models.IntegerField()),
                ('direccion_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movimiento', models.IntegerField()),
                ('iban', models.TextField(max_length=100)),
                ('monto', models.IntegerField()),
                ('tipo_operacion', models.TextField(max_length=200)),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField()),
                ('loan_type', models.TextField(max_length=200)),
                ('loan_date', models.TextField(max_length=500)),
                ('loan_total', models.IntegerField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace Web')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='tarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_id', models.IntegerField()),
                ('numero_tarjeta', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('fecha_emision', models.TextField(max_length=200)),
                ('fecha_vencimiento', models.TextField(max_length=50)),
                ('tipo_tarjeta_id', models.IntegerField()),
                ('marca_tarjeta_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
            ],
        ),
    ]
