# Generated by Django 4.0.6 on 2022-08-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.TextField(default='tipo', max_length=30),
        ),
    ]
