# Generated by Django 4.0.6 on 2022-08-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_clientes_tipo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='movimientos',
            name='id_movimiento',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='loan_id',
        ),
        migrations.RemoveField(
            model_name='tarjetas',
            name='tarjeta_id',
        ),
    ]
