# Generated by Django 4.0.6 on 2022-08-15 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_remove_clientes_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='loan_date',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='loan_type',
        ),
        migrations.AddField(
            model_name='prestamos',
            name='loanType',
            field=models.TextField(default='Personales', max_length=40),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 14, 21, 44, 7, 53438)),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='loan_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='loan_total',
            field=models.FloatField(default=0),
        ),
    ]
