# Generated by Django 4.0.6 on 2022-08-15 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_remove_prestamos_loan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 15, 13, 16, 16, 171420)),
        ),
    ]
