# Generated by Django 4.0.6 on 2022-08-15 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_alter_prestamos_loan_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='id_cliente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 15, 16, 27, 18, 261854, tzinfo=utc)),
        ),
    ]
