# Generated by Django 4.0.6 on 2022-08-15 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_prestamos_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 8, 15, 16, 27, 42, 218740, tzinfo=utc)),
        ),
    ]
