# Generated by Django 4.0.6 on 2022-08-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_alter_prestamos_loan_approved_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuenta',
        ),
        migrations.DeleteModel(
            name='empleado',
        ),
        migrations.DeleteModel(
            name='movimientos',
        ),
        migrations.DeleteModel(
            name='prestamos',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='tarjetas',
        ),
    ]
