# Generated by Django 4.0.6 on 2022-08-24 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clientes', '0008_delete_cuenta_delete_empleado_delete_movimientos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
