# Generated by Django 4.0.6 on 2022-08-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_clientes_created_at_clientes_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cuenta_id',
            field=models.IntegerField(default=-1),
        ),
    ]
