# Generated by Django 4.0.6 on 2022-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_remove_clientes_cuenta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='account_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
