# Generated by Django 4.0.6 on 2022-08-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_tarjetas_alter_project_options_project_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tarjetas',
        ),
    ]
