# Generated by Django 4.0.6 on 2022-08-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_delete_tarjetas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('tipo_tarjeta', models.TextField(max_length=20)),
                ('marca_tarjeta', models.TextField(max_length=20)),
                ('account_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
    ]
