# Generated by Django 4.0.6 on 2022-09-01 18:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamos_id_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 9, 1, 18, 52, 37, 797605, tzinfo=utc)),
        ),
    ]
