# Generated by Django 4.0.6 on 2022-09-01 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_alter_prestamos_loan_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 9, 1, 18, 53, 32, 629610, tzinfo=utc)),
        ),
    ]
