# Generated by Django 4.0.6 on 2022-09-01 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0006_alter_prestamos_loan_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='id_cuenta',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 9, 1, 19, 3, 44, 525686, tzinfo=utc)),
        ),
    ]
