# Generated by Django 4.0.6 on 2022-09-01 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_remove_prestamos_id_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='id_cliente',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='loan_approved_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 9, 1, 19, 4, 50, 273287, tzinfo=utc)),
        ),
    ]
